version: "3.8"
services:
    frontend-app:
        image: parrot-frontend
        restart: unless-stopped
        ports:
            - 8000:80
        extra_hosts:
            - "host.docker.internal:host-gateway"
        environment:
            BACKEND_PORT: 18200
    backend-app:
        image: parrot-backend
        restart: unless-stopped
        network_mode: host
        env_file: .env
        environment:
            NODE_ENV: production
            PORT: 18200
    zerotier-app:
        image: zerotier/zerotier:latest
        command:
            - ${ZEROTIER_ID}
        devices:
            - /dev/net/tun
        network_mode: host
        volumes:
            - "/var/lib/zerotier-one:/var/lib/zerotier-one"
        cap_add:
            - NET_ADMIN
            - SYS_ADMIN
        env_file: .env
