name: New version

on:
    workflow_dispatch:
        inputs:
            version:
                required: true
                type: string
                description: "Example: v1.0.0"

jobs:
    version:
        runs-on: ubuntu-latest
        permissions:
            contents: write
        steps:
            - uses: actions/checkout@v2
              with:
                  fetch-depth: 0
                  token: ${{ secrets.GITHUB_TOKEN }}
            - name: configure git user
              run: |
                  git config user.name "CI"
                  git config user.email "CI"
            - run: git add -A ./* && git tag -a ${{github.event.inputs.version}} -m '${{github.event.inputs.version}}' && git push --tags
